<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('students')->insert([[
            'nationality_id' => 1,
            'guardian_id' => 1,
            'name' => 'Lucius',
            'lastname' => 'Payne',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '2984724',
            'birth_date' => '2003/12/12',
            'sex' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 2,
            'guardian_id' => 2,
            'name' => 'Chad',
            'lastname' => 'Sanchez',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '3565445',
            'birth_date' => '2003/12/12',
            'sex' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 3,
            'guardian_id' => 1,
            'name' => 'Michael',
            'lastname' => 'Wise',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '8734373',
            'birth_date' => '2003/12/12',
            'sex' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 2,
            'guardian_id' => 2,
            'name' => 'Sharon',
            'lastname' => 'Williams',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '9842438',
            'birth_date' => '2003/12/12',
            'sex' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 2,
            'guardian_id' => 3,
            'name' => 'Willis',
            'lastname' => 'McGee',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '6387258',
            'birth_date' => '2004/12/12',
            'sex' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 1,
            'guardian_id' => 4,
            'name' => 'Lynn',
            'lastname' => 'Powell',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '1824824',
            'birth_date' => '2005/12/12',
            'sex' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 1,
            'guardian_id' => 5,
            'name' => 'Christian',
            'lastname' => 'Padilla',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '839483',
            'birth_date' => '2008/12/12',
            'sex' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 3,
            'guardian_id' => 5,
            'name' => 'Claudia',
            'lastname' => 'Stapleton',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '4984289',
            'birth_date' => '1997/12/12',
            'sex' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 4,
            'guardian_id' => 3,
            'name' => 'Karina',
            'lastname' => 'Bruce',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '9479384',
            'birth_date' => '1997/12/12',
            'sex' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 4,
            'guardian_id' => 2,
            'name' => 'William',
            'lastname' => 'Bronson',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '6387935',
            'birth_date' => '1997/12/12',
            'sex' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 5,
            'guardian_id' => 1,
            'name' => 'Tommy',
            'lastname' => 'Lumpkin',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '7384738',
            'birth_date' => '1997/12/12',
            'sex' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 5,
            'guardian_id' => 3,
            'name' => 'Dean',
            'lastname' => 'Hopkins',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '6438742',
            'birth_date' => '1997/12/12',
            'sex' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 5,
            'guardian_id' => 4,
            'name' => 'Rachel',
            'lastname' => 'Parsons',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '4729824',
            'birth_date' => '1997/12/12',
            'sex' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 2,
            'guardian_id' => 2,
            'name' => 'Pearl',
            'lastname' => 'Sartin',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '8348734',
            'birth_date' => '1997/12/12',
            'sex' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 4,
            'guardian_id' => 1,
            'name' => 'Ralph',
            'lastname' => 'McCleery',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '3872832',
            'birth_date' => '1997/12/12',
            'sex' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 3,
            'guardian_id' => 5,
            'name' => 'Susan',
            'lastname' => 'Wentzel',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '1938234',
            'birth_date' => '1997/12/12',
            'sex' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 2,
            'guardian_id' => 3,
            'name' => 'Sylvia',
            'lastname' => 'Bernabe',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '1429882',
            'birth_date' => '1997/12/12',
            'sex' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 1,
            'guardian_id' => 1,
            'name' => 'Thomas',
            'lastname' => 'Mello',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '9827242',
            'birth_date' => '1997/12/12',
            'sex' => 'Masculino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 5,
            'guardian_id' => 2,
            'name' => 'Anna',
            'lastname' => 'Pinner',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '7284944',
            'birth_date' => '1997/12/12',
            'sex' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'nationality_id' => 4,
            'guardian_id' => 4,
            'name' => 'Laura',
            'lastname' => 'Bryan',
            'document_type' => 'Cédula de Identidad',
            'document_number' => '2742844',
            'birth_date' => '1997/12/12',
            'sex' => 'Femenino',
            'created_at' => now(),
            'updated_at' => now(),
        ]]);
    }
}
